
/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2019 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_DHERR_H
# define HEADER_DHERR_H

# ifndef HEADER_SYMHACKS_H
#  include <openssl/symhacks.h>
# endif

# include <openssl/opensslconf.h>

# ifndef OPENSSL_NO_DH

#  ifdef  __cplusplus
extern "C"
#  endif
int ERR_load_DH_strings(void);

/*
 * DH function codes.
 */
#  define DH_F_COMPUTE_KEY                                 102
#  define DH_F_DHPARAMS_PRINT_FP                           101
#  define DH_F_DH_BUILTIN_GENPARAMS                        106
#  define DH_F_DH_CHECK_EX                                 121
#  define DH_F_DH_CHECK_PARAMS_EX                          122
#  define DH_F_DH_CHECK_PUB_KEY_EX                         123
#  define DH_F_DH_CMS_DECRYPT                              114
#  define DH_F_DH_CMS_SET_PEERKEY                          115
#  define DH_F_DH_CMS_SET_SHARED_INFO                      116
#  define DH_F_DH_METH_DUP                                 117
#  define DH_F_DH_METH_NEW                                 118
#  define DH_F_DH_METH_SET1_NAME                           119