/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2019 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_PKCS12ERR_H
# define HEADER_PKCS12ERR_H

# ifndef HEADER_SYMHACKS_H
#  include <openssl/symhacks.h>
# endif

# ifdef  __cplusplus
extern "C"
# endif
int ERR_load_PKCS12_strings(void);

/*
 * PKCS12 function codes.
 */
# define PKCS12_F_OPENSSL_ASC2UNI                         121
# define PKCS12_F_OPENSSL_UNI2ASC                         124
# define PKCS12_F_OPENSSL_UNI2UTF8                        127
# define PKCS12_F_OPENSSL_UTF82UNI                        129
# define PKCS12_F_PKCS12_CREATE        